# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  buildAgent: 'ubuntu-latest'

stages:
  - stage:
    displayName: 'Build on code push'
    jobs:
      - job:
        pool: 
         vmImage: $(buildAgent)
        steps:
          - script: dotnet build --configuration $(buildConfiguration) TekkiGurus.WebAppDemo
            displayName: 'dotnet build $(buildConfiguration)'
          - script: dotnet publish --no-build  --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) TekkiGurus.WebAppDemo
            displayName: 'dotnet publish $(buildConfiguration)'   
 
  - stage:
    displayName: 'Deploy to Azure'
    jobs:
      - job:
        pool: 
         vmImage: $(buildAgent)
        steps:
          - script: echo 'Hello World'
  
# pool:
#   vmImage: ubuntu-latest


# steps:
# - script: dotnet build --configuration $(buildConfiguration) TekkiGurus.WebAppDemo
#   displayName: 'dotnet build $(buildConfiguration)'
# - script: dotnet publish --no-build  --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) TekkiGurus.WebAppDemo
#   displayName: 'dotnet publish $(buildConfiguration)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'