# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  buildAgent: 'ubuntu-latest'

stages:
  - stage:
    displayName: 'Build on code push'
    jobs:
      - job:
        displayName: 'Build code and publish artifacts'
        pool: 
         vmImage: $(buildAgent)
        steps:
          - script: dotnet build --configuration $(buildConfiguration) TekkiGurus.WebAppDemo
            displayName: 'dotnet build $(buildConfiguration)'
          - script: dotnet publish --no-build  --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory) TekkiGurus.WebAppDemo
            displayName: 'dotnet publish $(buildConfiguration)'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(build.artifactstagingdirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish build to artifacts directory'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'
 
  - stage:
    displayName: 'Deploy to Azure'
    jobs:
      - job:
        displayName: 'Deploy artifacts from build stage to Azure'
        pool: 
         vmImage: $(buildAgent)
        steps:
        - task: DownloadBuildArtifacts@1
          displayName: 'Download build artifacts'
          inputs:
            buildType: 'current'
            downloadType: 'specific'
            itemPattern: '**/*.zip'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'MVP Subscription(6e16946d-c30b-48c0-a0de-26f1159aa94f)'
            appType: 'webAppLinux'
            appName: 'gwltekki-webapp'
            package: '$(System.ArtifactsDirectory)/**/*.zip'
            runtimeStack: 'DOTNETCORE|7.0'